64 bit support

diff --git a/EmberOS/CustomPiOS/src/modules/docker/start_chroot_script b/EmberOS/CustomPiOS/src/modules/docker/start_chroot_script
--- a/EmberOS/CustomPiOS/src/modules/docker/start_chroot_script
+++ b/EmberOS/CustomPiOS/src/modules/docker/start_chroot_script
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # CustomPiOS module : docker
 # Original script written by Damien DALY (https://github.com/MaitreDede/)
+# Changes by Guy Sheffer
 # GPL V3
 ########
 set -ex
@@ -8,8 +9,48 @@ set -ex
 source /common.sh
 install_cleanup_trap
 
-curl -sSL get.docker.com | sh && usermod pi -aG docker
+if [ "${BASE_DISTRO}" == "raspbian" ]; then
+        curl -sSL get.docker.com | sh
+elif [ "${BASE_DISTRO}" == "ubuntu" ]; then
+    if [ "${BASE_ARCH}" == "aarch64" ] || [ "${BASE_ARCH}" == "arm64" ]; then
+        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+        add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu disco stable"
+    else
+        echo "Error, not implemented Ubuntu 32bit"
+	exit 1
+    fi
+    apt-get update
+    apt-get install -y docker-ce
+fi
+
+if [ "${DOCKER_ADD_USER_TO_GROUP}" == "yes" ]; then
+    usermod "${BASE_USER}" -aG docker
+fi
+
+if [ "${DOCKER_COMPOSE}" == "yes" ]; then
+    apt-get install -y python3 python3-distutils python3-dev python3-testresources gcc libffi-dev build-essential libssl-dev cargo
+    # Docker-compose
+    wget https://bootstrap.pypa.io/get-pip.py -O - | python3
+    pip3 install --ignore-installed PyYAML
+    pip3 install docker-compose
+fi
+
+
+if [ "${DOCKER_COMPOSE_BOOT}" == "yes" ]; then
+    unpack /filesystem/root /
+    unpack /filesystem/boot /"${BASE_BOOT_MOUNT_PATH}"
+    
+    if [ "${DOCKER_COMPOSE_BOOT_PATH}" == "default" ]; then
+        DOCKER_COMPOSE_BOOT_PATH_ACTUAL="/${BASE_BOOT_MOUNT_PATH}"/docker-compose
+    else
+        DOCKER_COMPOSE_BOOT_PATH_ACTUAL="${DOCKER_COMPOSE_BOOT_PATH}"
+    fi
+    sed -i "s@DOCKER_COMPOSE_BOOT_PATH_PLACEHOLDER@${DOCKER_COMPOSE_BOOT_PATH_ACTUAL}@g" /etc/systemd/system/docker-compose.service
+    sed -i "s@DOCKER_COMPOSE_BOOT_PATH_PLACEHOLDER@${DOCKER_COMPOSE_BOOT_PATH_ACTUAL}@g" /usr/bin/start_docker_compose
+    sed -i "s@DOCKER_COMPOSE_BOOT_PATH_PLACEHOLDER@${DOCKER_COMPOSE_BOOT_PATH_ACTUAL}@g" /usr/bin/stop_docker_compose
+    systemctl enable docker-compose.service
+fi
 
 #cleanup
-apt-get autoclean 
+apt-get clean
 apt-get autoremove -y
diff --git a/EmberOS/CustomPiOS/src/nightly_build_scripts/custompios_nightly_build b/EmberOS/CustomPiOS/src/nightly_build_scripts/custompios_nightly_build
--- a/EmberOS/CustomPiOS/src/nightly_build_scripts/custompios_nightly_build
+++ b/EmberOS/CustomPiOS/src/nightly_build_scripts/custompios_nightly_build
@@ -2,24 +2,28 @@
 set -x
 set -e
 
-whoami
-
 export DIST_PATH=/distro
 export CUSTOM_PI_OS_PATH=/CustomPiOS
 
-if [ "$#" -gt 0 ]; then
-  BUILD_VARIANT="$1"
-else
-  BUILD_VARIANT=default
-fi
+source "$CUSTOM_PI_OS_PATH/argparse.bash" || exit 1
+argparse "$@" <<EOF || exit 1
+
+parser.add_argument('WORKSPACE_SUFFIX', nargs='?', default="default", help="The workspace folder suffix used folder")
+parser.add_argument('-r', '--rpi_imager', action='store_true', help='Create a rpi-imager snipplet to be published')
+parser.add_argument('-u', '--rpi_imager_url', type=str, default="MISSING_URL", help='url to the uploaded image url')
+EOF
 
 WORKSPACE_POSTFIX=
-if [ $BUILD_VARIANT != 'default' ]; then
-  WORKSPACE_POSTFIX=-$BUILD_VARIANT
+if [ "${WORKSPACE_SUFFIX}" != 'default' ]; then
+  WORKSPACE_POSTFIX=-"${WORKSPACE_SUFFIX}"
 fi
 
 #Update repos used
 #sudo -u guy /home/guy/stuff/scripts/gitmirror/update_git_mirrors
+if [ "${SHA256}" == "yes" ]; then
+    echo "Saving image hash type sha256"
+    sha256sum "${IMG_FILENAME}" > "${IMG_FILENAME}".sha256
+fi
 
 for i in `lsof "${DIST_PATH}/workspace${WORKSPACE_POSTFIX}/mount" | awk '{print $2}'`; do kill -9 $i; done || true
 
@@ -36,12 +40,28 @@ pushd "${DIST_PATH}"
     #export OCTOPI_OCTOPRINT_REPO_BUILD='http://localhost/git/OctoPrint.git/'
     #export OCTOPI_MJPGSTREAMER_REPO_BUILD='http://localhost/git/mjpg-streamer.git/'
     #export OCTOPI_WIRINGPI_REPO_BUILD='http://localhost/git/wiringPi.git/'
-    ${CUSTOM_PI_OS_PATH}/build_custom_os $1
+    ${CUSTOM_PI_OS_PATH}/build_custom_os "${WORKSPACE_SUFFIX}"
     exit_code=$?
     if [ $exit_code -ne 0 ]; then
         echo "build script failed"
         exit $exit_code
     fi
-    bash -x ${CUSTOM_PI_OS_PATH}/release $1
+    EXTRA_FLAGS=""
+    if [ "${RPI_IMAGER}" == "yes" ]; then
+        echo "Creating a rpi-imager json snipplet"
+        EXTRA_FLAGS="--sha256"
+    fi
+    
+    bash -x ${CUSTOM_PI_OS_PATH}/release ${EXTRA_FLAGS} "${WORKSPACE_SUFFIX}"
+    
+    if [ "${RPI_IMAGER}" == "yes" ]; then
+        if [ -z "${CUSTOM_PI_OS_PATH}" ];then
+            echo "Error: you must have \${CUSTOM_PI_OS_PATH} to generate a rpi-imager snipplet"
+            exit 1
+        fi
+        source "${CUSTOM_PI_OS_PATH}/config" "${WORKSPACE_SUFFIX}"
+        "${CUSTOM_PI_OS_PATH}/make_rpi-imager-snipplet.py" --rpi_imager_url "${RPI_IMAGER_URL}" -- "${WORKSPACE_SUFFIX}"
+    fi
+    
     chmod 777 ${DIST_PATH}/workspace${WORKSPACE_POSTFIX}/*
 popd
